//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class g03_databaseEntities : DbContext
    {
        public g03_databaseEntities()
            : base("name=g03_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbMetodologias> tbMetodologias { get; set; }
        public virtual DbSet<tbProyectoRupFases> tbProyectoRupFases { get; set; }
        public virtual DbSet<tbProyectos> tbProyectos { get; set; }
        public virtual DbSet<tbProyectoUsuarios> tbProyectoUsuarios { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRupActividadAsignaciones> tbRupActividadAsignaciones { get; set; }
        public virtual DbSet<tbRupActividades> tbRupActividades { get; set; }
        public virtual DbSet<tbRupDocumentos> tbRupDocumentos { get; set; }
        public virtual DbSet<tbRupFases> tbRupFases { get; set; }
        public virtual DbSet<tbRupTiposDocumento> tbRupTiposDocumento { get; set; }
        public virtual DbSet<tbScrumBacklog> tbScrumBacklog { get; set; }
        public virtual DbSet<tbScrumDaily> tbScrumDaily { get; set; }
        public virtual DbSet<tbScrumDailyBacklog> tbScrumDailyBacklog { get; set; }
        public virtual DbSet<tbScrumSprints> tbScrumSprints { get; set; }
        public virtual DbSet<tbTareas> tbTareas { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbXpActividades> tbXpActividades { get; set; }
        public virtual DbSet<tbXpEntregas> tbXpEntregas { get; set; }
        public virtual DbSet<tbXpHistoriasUsuario> tbXpHistoriasUsuario { get; set; }
        public virtual DbSet<tbXpIteraciones> tbXpIteraciones { get; set; }
        public virtual DbSet<tbXpParejasProgramacion> tbXpParejasProgramacion { get; set; }
        public virtual DbSet<tbXpPlanningGame> tbXpPlanningGame { get; set; }
        public virtual DbSet<tbXpPruebasAceptacion> tbXpPruebasAceptacion { get; set; }
        public virtual DbSet<tbXpRefactorizacion> tbXpRefactorizacion { get; set; }
        public virtual DbSet<tbXpRetroalimentacion> tbXpRetroalimentacion { get; set; }
        public virtual DbSet<tbXpTest> tbXpTest { get; set; }
    }
}
