//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectoRupFases
    {
        public int idProyectoRupFase { get; set; }
        public int idProyecto { get; set; }
        public int idFase { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
    
        public virtual tbProyectos tbProyectos { get; set; }
        public virtual tbRupFases tbRupFases { get; set; }
    }
}
