//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProyectos()
        {
            this.tbProyectoUsuarios = new HashSet<tbProyectoUsuarios>();
            this.tbScrumBacklog = new HashSet<tbScrumBacklog>();
            this.tbScrumSprints = new HashSet<tbScrumSprints>();
            this.tbTareas = new HashSet<tbTareas>();
            this.tbXpActividades = new HashSet<tbXpActividades>();
            this.tbRupIteraciones = new HashSet<tbRupIteraciones>();
        }
    
        public int idProyecto { get; set; }
        public string nombreProyecto { get; set; }
        public string descripcionProyecto { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public int idUsuario { get; set; }
        public int idMetodologia { get; set; }
        public Nullable<int> idFase { get; set; }
    
        public virtual tbMetodologias tbMetodologias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectoUsuarios> tbProyectoUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbScrumBacklog> tbScrumBacklog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbScrumSprints> tbScrumSprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTareas> tbTareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbXpActividades> tbXpActividades { get; set; }
        public virtual tbRupFases tbRupFases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRupIteraciones> tbRupIteraciones { get; set; }
    }
}
