//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRupActividades
    {
        public int idActividad { get; set; }
        public int idFase { get; set; }
        public int idUsuario { get; set; }
        public int idRol { get; set; }
        public string nombreActividad { get; set; }
        public string descripcionActividad { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbRupFases tbRupFases { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
