//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRupDocumentos
    {
        public int idDocumento { get; set; }
        public int idTipoDocumento { get; set; }
        public string nombreArchivo { get; set; }
        public string rutaArchivo { get; set; }
        public string Version { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaSubida { get; set; }
        public int idFase { get; set; }
        public int idProyecto { get; set; }
    
        public virtual tbProyectos tbProyectos { get; set; }
        public virtual tbRupFases tbRupFases { get; set; }
        public virtual tbRupTiposDocumento tbRupTiposDocumento { get; set; }
    }
}
