//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRupDocumentacion
    {
        public int idDocumento { get; set; }
        public int idFase { get; set; }
        public string nombreDocumento { get; set; }
        public string contenidoDocumento { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
    
        public virtual tbRupFases tbRupFases { get; set; }
    }
}
