//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRupIteraciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbRupIteraciones()
        {
            this.tbRupActividades = new HashSet<tbRupActividades>();
            this.tbRupDocumentos = new HashSet<tbRupDocumentos>();
        }
    
        public int idIteracion { get; set; }
        public int idProyecto { get; set; }
        public string nombre { get; set; }
        public string objetivo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string Estado { get; set; }
        public int idFase { get; set; }
    
        public virtual tbProyectos tbProyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRupActividades> tbRupActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRupDocumentos> tbRupDocumentos { get; set; }
        public virtual tbRupFases tbRupFases { get; set; }
    }
}
