//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRupActividades
    {
        public int idActividad { get; set; }
        public int idIteracion { get; set; }
        public string descripcion { get; set; }
        public int idRol { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaLimite { get; set; }
    
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbRupIteraciones tbRupIteraciones { get; set; }
    }
}
