//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbScrumDaily
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbScrumDaily()
        {
            this.tbScrumDailyBacklog = new HashSet<tbScrumDailyBacklog>();
        }
    
        public int idDaily { get; set; }
        public int idSprint { get; set; }
        public System.DateTime fechaDaily { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbScrumDailyBacklog> tbScrumDailyBacklog { get; set; }
        public virtual tbScrumSprints tbScrumSprints { get; set; }
    }
}
