//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbScrumDailyBacklog
    {
        public int idDaily { get; set; }
        public int idBacklog { get; set; }
        public int idUsuario { get; set; }
        public string comentarioActividad { get; set; }
    
        public virtual tbScrumBacklog tbScrumBacklog { get; set; }
        public virtual tbScrumDaily tbScrumDaily { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
