//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbXpEntregas
    {
        public int idEntrega { get; set; }
        public int idIteracion { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> validadoPorCliente { get; set; }
    
        public virtual tbXpIteraciones tbXpIteraciones { get; set; }
    }
}
