//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbXpPruebasAceptacion
    {
        public int idPrueba { get; set; }
        public int idHistoria { get; set; }
        public string descripcion { get; set; }
        public string resultado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual tbXpHistoriasUsuario tbXpHistoriasUsuario { get; set; }
    }
}
