//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbXpPlanningGame
    {
        public int idPlan { get; set; }
        public int idIteracion { get; set; }
        public int idHistoria { get; set; }
        public Nullable<int> estimacionHoras { get; set; }
        public Nullable<int> prioridad { get; set; }
    
        public virtual tbXpHistoriasUsuario tbXpHistoriasUsuario { get; set; }
        public virtual tbXpIteraciones tbXpIteraciones { get; set; }
    }
}
