//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_ProyectoGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbXpTest
    {
        public int idTest { get; set; }
        public int idActividad { get; set; }
        public string descripcionTest { get; set; }
        public Nullable<System.DateTime> fechaTest { get; set; }
    
        public virtual tbXpActividades tbXpActividades { get; set; }
    }
}
