//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_GestionDeCambiosEntities : DbContext
    {
        public BD_GestionDeCambiosEntities()
            : base("name=BD_GestionDeCambiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCiclos> tbCiclos { get; set; }
        public virtual DbSet<tbDocumentos> tbDocumentos { get; set; }
        public virtual DbSet<tbElementos> tbElementos { get; set; }
        public virtual DbSet<tbMetodologias> tbMetodologias { get; set; }
        public virtual DbSet<tbProyectoCiclo> tbProyectoCiclo { get; set; }
        public virtual DbSet<tbProyectoElemento> tbProyectoElemento { get; set; }
        public virtual DbSet<tbProyectos> tbProyectos { get; set; }
        public virtual DbSet<tbProyectoUsuario> tbProyectoUsuario { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbSolicitudesCambio> tbSolicitudesCambio { get; set; }
        public virtual DbSet<tbTareas> tbTareas { get; set; }
        public virtual DbSet<tbTiposDocumento> tbTiposDocumento { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
    }
}
