//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDespliegues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDespliegues()
        {
            this.tbPasosDespliegue = new HashSet<tbPasosDespliegue>();
        }
    
        public int idDespliegue { get; set; }
        public int idSolicitudCambio { get; set; }
        public int idEntorno { get; set; }
        public int idUsuarioInicio { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string estado { get; set; }
        public string comentarios { get; set; }
    
        public virtual tbEntornosDespliegue tbEntornosDespliegue { get; set; }
        public virtual tbSolicitudesCambio tbSolicitudesCambio { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPasosDespliegue> tbPasosDespliegue { get; set; }
    }
}
