//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocumentos
    {
        public int idDocumento { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string nombreArchivo { get; set; }
        public string rutaArchivo { get; set; }
        public string version { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaSubida { get; set; }
        public string codCiclo { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> idUsuarioSubida { get; set; }
    
        public virtual tbCiclos tbCiclos { get; set; }
        public virtual tbProyectos tbProyectos { get; set; }
        public virtual tbTiposDocumento tbTiposDocumento { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
