//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPasosDespliegue
    {
        public int idPasoDespliegue { get; set; }
        public int idDespliegue { get; set; }
        public int orden { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public Nullable<int> idUsuarioCompletado { get; set; }
        public Nullable<System.DateTime> fechaCompletado { get; set; }
        public string notas { get; set; }
    
        public virtual tbDespliegues tbDespliegues { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
