//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProyectos()
        {
            this.tbDocumentos = new HashSet<tbDocumentos>();
            this.tbProyectoCiclo = new HashSet<tbProyectoCiclo>();
            this.tbProyectoElemento = new HashSet<tbProyectoElemento>();
            this.tbProyectoUsuario = new HashSet<tbProyectoUsuario>();
            this.tbSolicitudesCambio = new HashSet<tbSolicitudesCambio>();
        }
    
        public int idProyecto { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public int idUsuarioCreador { get; set; }
        public int idMetodologia { get; set; }
        public string codCicloActual { get; set; }
        public int estado { get; set; }
    
        public virtual tbCiclos tbCiclos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentos> tbDocumentos { get; set; }
        public virtual tbMetodologias tbMetodologias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectoCiclo> tbProyectoCiclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectoElemento> tbProyectoElemento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectoUsuario> tbProyectoUsuario { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSolicitudesCambio> tbSolicitudesCambio { get; set; }
    }
}
