//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectoCiclo
    {
        public int idProyectoCiclo { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public string codCiclo { get; set; }
        public Nullable<System.DateTime> inicioCiclo { get; set; }
        public Nullable<System.DateTime> finCiclo { get; set; }
    
        public virtual tbCiclos tbCiclos { get; set; }
        public virtual tbProyectos tbProyectos { get; set; }
    }
}
