//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudHistorial
    {
        public int idHistorial { get; set; }
        public int idSolicitudCambio { get; set; }
        public int pasoProceso { get; set; }
        public string nombrePasoProceso { get; set; }
        public System.DateTime fechaAccion { get; set; }
        public int idUsuarioAccion { get; set; }
        public string comentarios { get; set; }
        public string decision { get; set; }
    
        public virtual tbSolicitudesCambio tbSolicitudesCambio { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
