//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_GestionDeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudesCambio
    {
        public int idSolicitudCambio { get; set; }
        public string codigoDocumentoSolicitd { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public int idProyecto { get; set; }
        public int idUsuarioSolicitante { get; set; }
        public string objetivoSolicitud { get; set; }
        public string descripcionSolicitud { get; set; }
        public Nullable<int> idElementoAfectado { get; set; }
        public string impactoEstimado { get; set; }
        public string esfuerzoEstimado { get; set; }
        public Nullable<int> idUsuarioReceptor { get; set; }
        public Nullable<System.DateTime> fechaRecibida { get; set; }
        public int pasoActualProceso { get; set; }
        public Nullable<System.DateTime> fechaInicioImplementacionCambio { get; set; }
        public Nullable<System.DateTime> fechaCierreDelCambio { get; set; }
        public string observaciones { get; set; }
        public string estadoSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEstado { get; set; }
        public Nullable<System.DateTime> GiroJefeProyectoFecha { get; set; }
        public Nullable<System.DateTime> ModificacionVersionFecha { get; set; }
    
        public virtual tbProyectoElemento tbProyectoElemento { get; set; }
        public virtual tbProyectos tbProyectos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
